# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Riza Fathul Uzzy
description:      'Software engineering, technology and some random thoughts'
url:              http://msobhy.me
baseurl:          /
logo:             '/content/images/pp.png'

author:
  name:           'Mohamed Sobhy'
  url:            http://msobhy.me

paginate:         5

disqus_shortname: rizafu
google_analytics_token: UA-46852284-3

github:
  repo:           https://github.com/rizafu/rizafu.github.io
  user:           'rizafu'

twitter: '@rizafu'
facebook: 'RezaFathulUzzy'
google_plus: '+RizaFu'
linkedin: 'riza-fathul-uzzy'
gmail: 'rzfu324@gmail.com'

gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
